#!/bin/sh

name=`basename $0`
resolution=$1
length=$#
parameters="$2"

for (( i = 3; i <= ${length}; i++ )); do
    parameters="${parameters} '$i'"
done

echo "Starting ImageJ"
source /etc/profile
module load virtualgl
cat /proc/meminfo | grep MemTotal

DIR=`which ${name} | sed 's/\/bin\/'${name}'//g'`
cd ${DIR}
${DIR}/jre/bin/java -Xmx${resolution}m -jar ${DIR}/ij.jar "${parameters}"
